#cloud-config

package_update: true
package_upgrade: true

packages:
  - crypto-config
  - exim4
  - nginx
  - ssl-cert

runcmd:
  - sed -i -e '/listen .*80 default_server/ s/listen/# listen/' -e '/listen .*443 ssl default_server/ s/# //' -e '/# include snippets\/snakeoil.conf;/ s/# //' /etc/nginx/sites-available/default
  - sed -i '/ssl_protocols/ d' '/etc/nginx/nginx.conf'
  - echo 'include /var/lib/crypto-config/profiles/current/nginx.conf.d/*.conf;' > '/etc/nginx/conf.d/crypto-config.conf'
  - sed -i 's/2048/4096/' '/usr/share/ssl-cert/ssleay.cnf'
  - make-ssl-cert -f generate-default-snakeoil
  - sed -i '/parent_profile/ s/jq/jq -r/'
  - mkdir -p '/usr/share/crypto-config/profiles/default/openssl.conf.d'
  - sed -i '/Defines what/ i .include_if_exists /var/lib/crypto-config/profiles/current/exim' /etc/exim4/exim4.conf.template
  - echo > '/usr/share/crypto-config/profiles/default/exim'
  - echo tls_eccurve = "X25519:prime256v1:secp384r1:secp521r1" > '/usr/share/crypto-config/profiles/future/exim'
  - echo tls_require_ciphers = "PFS:-SHA1:-GROUP-FFDHE2048:-GROUP-FFDHE3072:-GROUP-FFDHE4096:-GROUP-FFDHE6144:-GROUP-FFDHE8192" >> '/usr/share/crypto-config/profiles/future/exim'
  - crypto-config generate-runtime-profiles
  - crypto-config switch {crypto_config_profile}
  - crypto-config status
  - systemctl restart exim4 nginx
