#!/bin/bash

set -e
set -u
shopt -s inherit_errexit

STATE_DIR='/var/lib/crypto-config'
STATE_PROFILES_DIR="${STATE_DIR}/profiles"

CURRENT="${STATE_PROFILES_DIR}/current"

help() {
  cat << EOF
Usage: crypto-config <command> ...
System-wide cryptography configuration profile management

Commands:
  get
  status
  switch <profile>
EOF
}

switch() {
  local target

  target="$1"

  if ! [[ -d "${STATE_PROFILES_DIR}/$1" ]]; then
    echo "'${target}' does not exist or is not a directory."
    exit 1
  fi

  ln -sfn "${target}" "${CURRENT}"

  echo "Profile switched to '${target}'."
}

get() {
  basename "$(readlink "${CURRENT}")"
}

status() {
  local current

  current="$(get)"

  printf "Current profile in '%s'\n" "${current}"
}

case "$1" in
  -h|-help|--help|help|h)
    help
    ;;
  get)
    shift
    get "$@"
    ;;
  status)
    shift
    status "$@"
    ;;
  switch)
    shift
    switch "$@"
    ;;
  *)
    printf "Unknown command '%s'\n" "$1"
    help
    ;;
esac
